# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Desktop/Estimating-battery-SOC-using-neural-network-main/FPGA/LSTM/LSTM.srcs/sources_1/ip/lstm_bias_hh_l1/lstm_bias_hh_l1.xci
# IP: The module: 'lstm_bias_hh_l1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/Estimating-battery-SOC-using-neural-network-main/FPGA/LSTM/LSTM.srcs/sources_1/ip/lstm_bias_hh_l1/lstm_bias_hh_l1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lstm_bias_hh_l1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Desktop/Estimating-battery-SOC-using-neural-network-main/FPGA/LSTM/LSTM.srcs/sources_1/ip/lstm_bias_hh_l1/lstm_bias_hh_l1.xci
# IP: The module: 'lstm_bias_hh_l1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/Estimating-battery-SOC-using-neural-network-main/FPGA/LSTM/LSTM.srcs/sources_1/ip/lstm_bias_hh_l1/lstm_bias_hh_l1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lstm_bias_hh_l1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
