webtalk_init -webtalk_dir D:/Desktop/Estimating-battery-SOC-using-neural-network-main/FPGA/LSTM/LSTM.sim/sim_1/behav/xsim/xsim.dir/fixed_point_adder_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat May  4 17:19:21 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "567fc5da-620c-4aff-9e9b-0c62bbe9ea31" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "36c2cb790e234af5a59558ea676665ce" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2096 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "105 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7424_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2115622373 -regid "" -xml D:/Desktop/Estimating-battery-SOC-using-neural-network-main/FPGA/LSTM/LSTM.sim/sim_1/behav/xsim/xsim.dir/fixed_point_adder_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Desktop/Estimating-battery-SOC-using-neural-network-main/FPGA/LSTM/LSTM.sim/sim_1/behav/xsim/xsim.dir/fixed_point_adder_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Desktop/Estimating-battery-SOC-using-neural-network-main/FPGA/LSTM/LSTM.sim/sim_1/behav/xsim/xsim.dir/fixed_point_adder_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
